version: "3.8"

services:
  ntfy0:
    image: binwiederhier/ntfy:latest
    container_name: ntfy0
    command:
      - serve
    environment:
      - TZ=UTC # optional: set desired timezone
    user: "1000:1000"
    volumes:
      - ./ntfy/cache:/var/cache/ntfy
      - ./ntfy/config:/etc/ntfy
      - ./ntfy/attachments:/var/cache/attachments
    restart: unless-stopped

  crawlers:
    build: .
    container_name: crawlers
    command: [ "npm", "run", "crawlers" ]
    <<:
      &shared
      image: tka85/price-snitch
      user: "1000:1000"
      environment:
        - DEBUG=price-snitch:*
      volumes:
        - ./priceSnitch.db:/home/node/priceSnitch.db
        - ./priceSnitch.db-shm:/home/node/priceSnitch.db-shm
        - ./priceSnitch.db-wal:/home/node/priceSnitch.db-wal
        - ./config.json:/home/node/config.json
      restart: unless-stopped

  notifiers:
    depends_on:
      - crawlers
    <<: *shared
    container_name: notifiers
    command: [ "npm", "run", "notifiers" ]
