CREATE TABLE IF NOT EXISTS `page`(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    url VARCHAR(2000) NOT NULL,
    descr VARCHAR(1000),
    currency VARCHAR(20)    
);

CREATE TABLE IF NOT EXISTS `price`(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    amount VARCHAR(30) NOT NULL,
    page_id INTEGER NOT NULL,
    FOREIGN KEY (page_id) REFERENCES page(id) ON DELETE CASCADE ON UPDATE CASCADE
);
