base-url: "http://ntfy0"
listen-http: ":8080"
#listen-https: ":8443"
#key-file: "/etc/ntfy/private.key"
#cert-file: "/etc/ntfy/cert.crt"
cache-file: "/var/cache/ntfy/cache.db"
cache-duration: "24h"
attachment-cache-dir: "/var/cache/ntfy/attachments"
keepalive-interval: "76s"
